name: build
on: [pull_request, push]
jobs:
  arduino-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Arduino-CLI
        run: bash ci/build-arduino.sh

  pio-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bash ci/build-platformio.sh

      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            .pio/build/*/firmware.bin
            .pio/build/*/firmware.elf
            .pio/build/*/spiffs.bin
